common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: viz
  password: viz
  min_messages: warning

  #host: localhost
  #port: 5432
  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

development:
  <<: *common
  database: vizir_development

test:
  <<: *common
  database: vizir_test

production:
  <<: *common
  database: vizir_production
